# Generated by Django 4.2 on 2024-07-15 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user_is_active_user_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='app_catrgory',
        ),
        migrations.RemoveField(
            model_name='user',
            name='app_link',
        ),
        migrations.RemoveField(
            model_name='user',
            name='app_name',
        ),
        migrations.CreateModel(
            name='APP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_link', models.CharField(blank=True, default='', max_length=100)),
                ('app_catrgory', models.CharField(blank=True, default='', max_length=100)),
                ('app_name', models.CharField(blank=True, default='', max_length=100)),
                ('image', models.ImageField(blank=True, default='null', null=True, upload_to='')),
                ('points', models.CharField(blank=True, default='', max_length=100)),
                ('user', models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
