# Generated by Django 4.2 on 2024-07-15 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_user_app_catrgory_remove_user_app_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='app_sub_category',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
