# Generated by Django 4.2 on 2024-07-15 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_app_app_sub_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='points',
            field=models.IntegerField(blank=True, default='', max_length=100),
        ),
    ]
