# Generated by Django 5.0.7 on 2024-07-17 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_app_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='points',
            field=models.IntegerField(blank=True, default=''),
        ),
    ]
